name: Build and test

on:
  schedule:
    - cron:  '0 5 * * *'

  workflow_dispatch:
    inputs:
      run_with_ssh:
        description: Run with SSH
        type: boolean
        default: false
      skip_uat:
        description: Skip user-acceptance tests (built-in tests still run)
        type: boolean
        default: false
      skip_tests:
        description: Skip all tests (use with SSH to manually test)
        type: boolean
        default: false
      skip_os:
        description: Skip jobs for an OS - use space-delimited list of macos, ubuntu, or windows
        type: string
        default: ''
      skip_python: Skip jobs for a Python version - use space-delimited list of 3.6, 3.7, 3.8, 3.9, or 3.10

jobs:
  build-posix:
    name: Build - POSIX
    runs-on: ${{ matrix.os }}
    if: ${{ !contains(inputs.skip_os, matrix.os) && !contains(inputs.skip_python, matrix.python-version) }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        python-version:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
          - 3.10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Configure SSH
        if: ${{ (success() || failure()) && inputs.run_with_ssh }}
        # ssh action (below) waits for a 'continue' sentinel - we want
        # the job to continue while ssh is available for connections
        run: touch continue

      - name: Start SSH
        if: ${{ (success() || failure()) && inputs.run_with_ssh }}
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true

      - name: Build package
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python setup.py bdist_wheel

      - name: Install package
        run: |
          python -m venv test-env
          test-env/bin/pip install --upgrade pip
          test-env/bin/pip install dist/*.whl

      - name: Install test requirements
        # uat tests install test requirements as a part of the test
        # suite - these must not be installed ahead of time
        if: ${{ inputs.skip_uat }}
        run: |
          test-env/bin/pip install -r guild/tests/requirements.txt

      - name: Configure environment for tests
        # git config required by Guild tests that run git commands
        run: |
          git config --global user.name unused
          git config --global user.email unused@localhost
          git config --global init.defaultBranch main

      - name: Run built-in tests
        if: ${{ !inputs.skip_tests && inputs.skip_uat }}
        env:
          GUILD_START_THRESHOLD: 1.0
        run: |
          test-env/bin/guild check -nT

      - name: Run user acceptance tests
        if: ${{ !inputs.skip_tests && !inputs.skip_uat }}
        env:
          WORKSPACE: /tmp/guild-uat
          EXAMPLES: examples
          UAT_SKIP: remote-*,hiplot-*
          GUILD_START_THRESHOLD: 1.0
          DASK_SPEEDUP_THRESHOLD: 0
        run: |
          test-env/bin/guild check --force-uat

      - name: Keep server alive for SSH (cancel workflow to terminate)
        if: ${{ (success() || failure()) && inputs.run_with_ssh }}
        run: sleep 3600

  build-windows:
    name: Build - Windows
    runs-on: windows-latest
    if: ${{ !contains(inputs.skip_os, 'windows') && !contains(inputs.skip_python, matrix.python-version) }}

    strategy:
      fail-fast: false
      matrix:
        # Omitting 3.6 on Windows due to [issues installing test
        # reqs](https://github.com/guildai/guildai/runs/8052694671)
        # and 3.6 end-of-life.
        python-version:
          - 3.7
          - 3.8
          - 3.9
          - 3.10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Configure SSH
        if: ${{ (success() || failure()) && inputs.run_with_ssh }}
        # ssh action (below) waits for a 'continue' sentinel - we want
        # the job to continue while ssh is available for connections
        run: touch continue

      - name: Start SSH
        if: ${{ (success() || failure()) && inputs.run_with_ssh }}
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true

      - name: Build package
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python setup.py bdist_wheel

      - name: Install package
        run: |
          python -m venv test-env
          test-env\scripts\python -m pip install --upgrade pip
          pwsh -Command 'test-env\scripts\pip install $(ls dist)'

      - name: Install test requirements
        # setuptools==58 is a workaround for an issue described in
        # https://stackoverflow.com/questions/69100275/error-while-downloading-the-requirements-using-pip-install-setup-command-use-2
        # In our case we get 'error in pywin32-ctypes setup command:
        # use_2to3 is invalid' when installing test reqs on some
        # versions of Windows. This can be removed when pywin32-ctypes
        # drops Python 2 support.
        run: |
          test-env\scripts\pip install setuptools==58
          test-env\scripts\pip install -r guild\tests\requirements.txt

      - name: Configure environment for tests
        # - git config required by Guild tests that run git commands
        # - test-env\Tmp used as TMPDIR for tests (keeps tmp files on
        #   same volume as project)
        run: |
          git config --global user.name unused
          git config --global user.email unused@localhost
          git config --global init.defaultBranch main
          mkdir \Tmp -Force

      - name: Run built-in tests
        if: ${{ !inputs.skip_tests }}
        env:
          GUILD_START_THRESHOLD: 1.0
          TMPDIR: \Tmp
        run: |
          test-env\scripts\guild check -nT

      - name: Keep server alive for SSH (cancel workflow to terminate)
        if: ${{ (success() || failure()) && inputs.run_with_ssh }}
        run: Start-Sleep 3600
