# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package to PyPI

env:
  NON_INTERACTIVE_CI: true
  TERM: xterm-256color
  WORKSPACE: test-env
  UAT_SKIP: remote-*,hiplot-*
  COLUMNS: 999
  EXAMPLES: examples
  GUILD_START_THRESHOLD: 2.0
  GUILD_SHELL: bash
  DASK_SPEEDUP_THRESHOLD: 1.2

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Git tags
        run: git fetch --prune --unshallow --tags -f
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
      - name: Build package
        run: |
          python setup.py bdist_wheel
          python setup.py sdist
      - name: Cache built wheel
        uses: actions/cache@v2
        env:
          cache-name: cache-built-wheel-${{ github.ref }}
        with:
          path: dist
          key: key-${{ github.ref }}

  validate:
    runs-on: ${{ matrix.sys.os }}
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        sys:
         # - { os: windows-latest, shell: 'bash' }
         - { os: ubuntu-latest,  shell: bash }
         - { os: macos-latest,   shell: bash }
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
        exclude:
          - sys:
              os: macos-latest
            python-version: 3.7  # there's a strange distutils error about missing distutils.sysconfig. We're punting and ignoring it for now.
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup git user
        run: |
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git config --global init.defaultBranch main
      - name: Use built wheel
        uses: actions/cache@v2
        env:
          cache-name: cache-built-wheel-${{ github.ref }}
        with:
          path: dist
          key: key-${{ github.ref }}
      - name: Run UAT tests
        run: |
          python -m pip install --upgrade dist/*.whl
          guild init -y --no-progress --name guild-test --guild dist/*.whl ./test-env
          source "$(find test-env -iname activate | awk '{ print length, $0 }' | sort -n -s | cut -d" " -f2- | head -n 1)"
          guild check -v --offline
          guild check --uat

  deploy-to-test-pypi:
    runs-on: ubuntu-latest
    needs: [validate]
    if: contains(github.ref, 'dev') || contains(github.ref, 'rc' )
    steps:
      - name: Use built wheel
        uses: actions/cache@v2
        env:
          cache-name: cache-built-wheel-${{ github.ref }}
        with:
          path: dist
          key: key-${{ github.ref }}
      - name: Publish package to test PyPI
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
      - name: Add GitHub Release entry
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*

  deploy-to-pypi:
    runs-on: ubuntu-latest
    needs: [validate]
    if: "! (contains(github.ref, 'dev') || contains(github.ref, 'rc' ))"
    steps:
      - name: Use built wheel
        uses: actions/cache@v2
        env:
          cache-name: cache-built-wheel-${{ github.ref }}
        with:
          path: dist
          key: key-${{ github.ref }}
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
      - name: Add GitHub Release entry
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
